load_module modules/ngx_http_geoip2_module.so;

events {
    worker_connections 1024;
}

http {
    map $http_x_forwarded_for $client_ip {
        "~^\s*([^, ]+)" $1;
        default       $remote_addr;
    }

    geoip2 /etc/nginx/geo/GeoLite2-Country.mmdb {
        $geoip2_country_code default=XX source=$client_ip country iso_code;
    }

    map $geoip2_country_code $region {
        default        europe;

        VN asia;
        JP asia;
        KR asia;
        CN asia;
        SG asia;
        TH asia;
        ID asia;
        PH asia;
        IN asia;
        MY asia;
        HK asia;
        TW asia;

        GB europe;
        DE europe;
        FR europe;
        ES europe;
        IT europe;
        NL europe;
        PL europe;
        SE europe;
        BE europe;
        PT europe;
    }

    map $region $region_target {
        asia   "minikube:31306";
        europe "minikube:31306";
    }

    map $region $region_host {
        asia   asia.game.local;
        europe europe.game.local;
    }

    map $geoip2_country_code $is_blocked_country {
        default   0;
        XX        1;
    }

    limit_req_zone $client_ip zone=router_limit:10m rate=10r/s;

    resolver 127.0.0.11 valid=30s;

    server {
        listen 443 ssl;
        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        location / {
            if ($is_blocked_country) {
                return 403 "Access denied: country not allowed\n";
            }

            limit_req zone=router_limit burst=20 nodelay;
            limit_req_status 429;

            add_header X-Detected-Country $geoip2_country_code always;
            add_header X-Routed-Region $region always;

            set $target https://$region_target;
            proxy_pass $target;
            proxy_ssl_server_name on;
            proxy_ssl_name $region_host;
            proxy_ssl_verify off;
            proxy_set_header Host $region_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /router-health {
            return 200 "global router is up\n";
            add_header Content-Type text/plain;
        }
    }

    # server {
    #     listen 80;

    #     location / {
    #         if ($is_blocked_country) {
    #             return 403 "Access denied: country not allowed\n";
    #         }

    #         limit_req zone=router_limit burst=20 nodelay;
    #         limit_req_status 429;

    #         add_header X-Detected-Country $geoip2_country_code always;
    #         add_header X-Routed-Region $region always;

    #         set $target https://$region_target;
    #         proxy_pass $target;
    #         proxy_ssl_server_name on;
    #         proxy_ssl_name $region_host;
    #         proxy_ssl_verify off;
    #         proxy_set_header Host $region_host;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto https;
    #     }

    #     location /router-health {
    #         return 200 "global router is up\n";
    #         add_header Content-Type text/plain;
    #     }
    # }
}
