services:
  global-router:
    build: ./global-router
    container_name: global-router
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - ./global-router/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./global-router/geo:/etc/nginx/geo:ro
      - ./global-router/certs:/etc/nginx/certs:ro
    networks:
      default:
        aliases: []

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: waf-global
    ports:
      - "9082:8080"
      - "9444:8443"
    environment:
      - BACKEND=https://global-router:443
      - PARANOIA=1
      - ANOMALY_INBOUND=5
    depends_on:
      - global-router
    networks:
      default:
        aliases: []

networks:
  default:
    external: true
    name: minikube
