services:
  backend1:
    image: node:20-alpine
    container_name: backend1
    working_dir: /app
    volumes:
      - ./backend:/app
    command: [ "node", "server.js" ]
    environment:
      - SERVER_ID=1
    networks:
      - lb-net

  backend2:
    image: node:20-alpine
    container_name: backend2
    working_dir: /app
    volumes:
      - ./backend:/app
    command: [ "node", "server.js" ]
    environment:
      - SERVER_ID=2
      - SLOW_MS=1000
    networks:
      - lb-net

  backend3:
    image: node:20-alpine
    container_name: backend3
    working_dir: /app
    volumes:
      - ./backend:/app
    command: [ "node", "server.js" ]
    environment:
      - SERVER_ID=3
      - SLOW_MS=500
    networks:
      - lb-net

  haproxy-lb:
    image: haproxy:latest
    container_name: haproxy-lb
    ports:
      - "8081:80" # Traffic chính
      - "8444:443"
      - "8404:8404" # Stats Dashboard trực quan
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/certs:/usr/local/etc/haproxy/certs:ro
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - lb-net

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: waf
    ports:
      - "8082:8080"
      - "8445:8443"
    environment:
      - BACKEND=https://haproxy-lb:443
      - PARANOIA=1 # Mức độ nghiêm ngặt của luật (1=lỏng nhất, 4=chặt nhất)
      - ANOMALY_INBOUND=5 # Ngưỡng điểm bất thường để chặn request (mặc định CRS: 5)
    depends_on:
      - haproxy-lb
    networks:
      - lb-net

networks:
  lb-net:
    driver: bridge
